name: Pull request workflow
on: [pull_request]
jobs:
  Install-Sync-Build-Start-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install doppler cli
        uses: dopplerhq/cli-action@v1
      - name: Install dependencies
        run: npm i
      - name: Synchronise database
        run: doppler run -- npm run db:sync
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      - name: Build packages
        run: doppler run -- npm run build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      - name: Start application server and run e2e tests
        run: doppler run -- npx start-server-and-test start http://localhost:8080 test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
